// <auto-generated />
using System;
using Columbus.Welkom.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Columbus.Welkom.Application.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.LeagueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("League")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("league", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.OwnerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Club")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("owner", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RingNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RingNumber");

                    b.HasIndex("Year");

                    b.ToTable("pigeon", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonRaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mark")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Mark");

                    b.HasIndex("PigeonId");

                    b.HasIndex("RaceId");

                    b.ToTable("pigeon_race", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonSwapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoupledPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoupledPlayerId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PigeonId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Year");

                    b.ToTable("pigeon_swap", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.RaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Number");

                    b.ToTable("race", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.SelectedYearPigeonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PigeonId");

                    b.ToTable("selected_year_pigeon", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.SelectedYoungPigeonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PigeonId");

                    b.ToTable("selected_young_pigeon", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdOwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirstOwnerId");

                    b.HasIndex("SecondOwnerId");

                    b.HasIndex("ThirdOwnerId");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.LeagueEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Owner")
                        .WithMany("Pigeons")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonRaceEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.PigeonEntity", "Pigeon")
                        .WithMany("PigeonRaces")
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.RaceEntity", "Race")
                        .WithMany("PigeonRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pigeon");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonSwapEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "CoupledPlayer")
                        .WithMany()
                        .HasForeignKey("CoupledPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.PigeonEntity", "Pigeon")
                        .WithMany()
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoupledPlayer");

                    b.Navigation("Owner");

                    b.Navigation("Pigeon");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.SelectedYearPigeonEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.PigeonEntity", "Pigeon")
                        .WithMany()
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pigeon");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.SelectedYoungPigeonEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.PigeonEntity", "Pigeon")
                        .WithMany()
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pigeon");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.TeamEntity", b =>
                {
                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "FirstOwner")
                        .WithMany()
                        .HasForeignKey("FirstOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "SecondOwner")
                        .WithMany()
                        .HasForeignKey("SecondOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Columbus.Welkom.Application.Models.Entities.OwnerEntity", "ThirdOwner")
                        .WithMany()
                        .HasForeignKey("ThirdOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstOwner");

                    b.Navigation("SecondOwner");

                    b.Navigation("ThirdOwner");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.OwnerEntity", b =>
                {
                    b.Navigation("Pigeons");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.PigeonEntity", b =>
                {
                    b.Navigation("PigeonRaces");
                });

            modelBuilder.Entity("Columbus.Welkom.Application.Models.Entities.RaceEntity", b =>
                {
                    b.Navigation("PigeonRaces");
                });
#pragma warning restore 612, 618
        }
    }
}
