name: Build and Release MAUI Windows App (Unpackaged)

on:
  push:
    tags:
      - '*'  # Triggers on any new tag

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: |
          dotnet workload install maui
          dotnet workload restore

      - name: Publish MAUI Windows app (Unpackaged)
        run: >
          dotnet publish Columbus.Welkom.Client\Columbus.Welkom.Client.csproj
          -f net8.0-windows10.0.19041.0
          -c Release
          -p:RuntimeIdentifierOverride=win10-x64
          -p:WindowsPackageType=None
          -o publish-output

      - name: Archive output (zip)
        run: Compress-Archive -Path publish-output\* -DestinationPath "${{ github.ref_name }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

